coins = [
    "1INCHBUSD",
    "AAVEBUSD",
    "ADABUSD",
    "ALGOBUSD",
    "APEBUSD",
    "ATOMBUSD",
    "AVAXBUSD",
    "BNBBUSD",
    "BTCBUSD",
    "COMPBUSD",
    "DOGEBUSD",
    "DOTBUSD",
    "ETCBUSD",
    "ETHBUSD",
    "FILBUSD",
    "LINKBUSD",
    "LTCBUSD",
    "MATICBUSD",
    "NEARBUSD",
    "QNTBUSD",
    "SHIBBUSD",
    "SOLBUSD",
    "SUSHIBUSD",
    "TRXBUSD",
    "UNIBUSD",
    "VETBUSD",
    "XLMBUSD",
    "XMRBUSD",
    "XRPBUSD",
]

coins = [{"symbol": c, "category": "spot"} for c in coins]
print(coins)
